### ISSUE TITLE
[develop] Three problems with failing generators

### ISSUE THREAD

**Issue by Benezivas** [Benezivas/algobattle-problems#10]
There are three problems that cause a `generator failed` when running them.
These are `oscm3`, `pairsum` and `tsptimewindows`.

Errors, extracted from logs, `\n` replaced with newlines by hand

oscm3:
```
`exit code: 1, error message:
Traceback (most recent call last):
  File "//main.py", line 8, in <module>
    json.dump(
  File "/usr/local/lib/python3.11/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks\n  File "/usr/local/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks\n  File "/usr/local/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type set is not JSON serializable
`
```
Pairsum:
```
`exit code: 1, error message:
Traceback (most recent call last):
  File "//main.py", line 4, in <module>
    with open("/input/size", "r") as input:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/input/size'
`
```

tsptimewindows:
```
"The tour visits a location too late."
```

**Comment by ImogenBits** [comment]
the first two are fixed with #9, #11. For the last I'm not sure what exactly the problem is supposed to express. Currently it says that every visit in the Euler tour needs to be within the vertex's time window, including both visits to the starting/ending vertex. If that is the intention behind the problem then the example solution we use is indeed wrong. Is only the first visit to each vertex supposed to be within the time window? In the literature I can find they usually define this problem to have a predefined starting/ending vertex without a time window, which we currently don't model at all

**Comment by Benezivas** [comment]
I have had another look at the original problem description and implementation back from 2019. In the original problem formulation, we have not stated whether the completion of the tour back to the initial node should be within the first node's time window.  Since the example only works with the assumption that the time window only has to be honored during the initial visit of a node, and since the example tour from the README on the old piece of code passes without errors, I think we have just implemented the new version "incorrectly", regarding the original intention of the problem. I do not mind changing it either way.
